### ISSUE TITLE
Libvips error 

### ISSUE THREAD

**Issue by Shaddox** [miku-gg/miku#45]
Good evening, 

I'm on Linux (PopOS 22.04) and I would like to run this project. I'm currently stuck with this error : 

```
/media/shaddox/Saturn/AI-Models/miku/node_modules/.pnpm/sharp@0.32.2/node_modules/sharp/lib/sharp.js:37
  throw new Error(help.join('\n'));
        ^
Error: 
Something went wrong installing the "sharp" module
libvips-cpp.so.42: cannot open shared object file: No such file or directory
Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/media/shaddox/Saturn/AI-Models/miku/node_modules/.pnpm/sharp@0.32.2/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Object.require.extensions.<computed> [as .js] (/media/shaddox/Saturn/AI-Models/miku/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.5_typescript@4.9.5/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1092:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/media/shaddox/Saturn/AI-Models/miku/node_modules/.pnpm/sharp@0.32.2/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
```

It seems brew did install it correctly, for what it's worth, however it's unable to find it. Any ideas?

**Comment by Shaddox** [comment]
Ah, I figured it out. 

Brew installed the library, but it installed it in `/home/linuxbrew/.linuxbrew` , so sharp couldn't find it. So all I had to do was just simlink it to my `/usr/bin/lib` directory, or more simply , just `sudo apt-get install libvips` and call it a day!
